pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/Deepak17460/Jenkins-with-Aws.git', 
                    branch: 'main',
                    credentialsId: '' 
                )
            }
        }

        stage('Build') {
            steps {
                script {
                    dir('Application') {
                        sh 'mvn clean package'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
