---
- name: Install Docker
  hosts: all
  become: true 

  tasks:
    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up Docker repository
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt and install Docker
      apt:
        update_cache: yes
        name: docker-ce docker-ce-cli containerd.io
        state: present

    - name: Install Docker module for Python
      pip:
        name: docker

    - name: Install six module for Python
      pip:
        name: six

    - name: Pull Docker image
      docker_image:
        name: dpcode72/java:1.0
        source: pull

    - name: Run Docker container
      docker_container:
        name: java_com_app
        image: dpcode72/java:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8004:8080"
