---
- name: Install Docker
  hosts: all
  become: true 

  tasks:
    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Install Docker module for Python
      pip:
        name: docker

    - name: Pull Docker image
      docker_image:
        name: dpcode72/java:1.0
        source: pull

    - name: Run Docker container
      docker_container:
        name: java_com_app
        image: dpcode72/java:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8004:8080"
