---
- hosts: all
  become_user: root
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Docker collection
      ansible.builtin.ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce and unzip
      apt:
        update_cache: yes
        name:
          - docker-ce
          - unzip
        state: latest

    - name: Install Docker module for Python
      pip:
        name: docker

    - name: Install six module for Python
      pip:
        name: six

    - name: Pull the custom Docker image
      community.docker.docker_image:
        name: dpcode72/java:1.0
        source: pull

    - name: Run the custom Docker container
      community.docker.docker_container:
        name: java_com_app
        image: dpcode72/java:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8004:8080"
