- name: Install Docker
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create symbolic link for Python
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Enable the Docker service
      systemd:
        name: docker
        enabled: yes

    - name: Start the Docker service
      systemd:
        name: docker
        state: started
